[package]
name = "qlogicae-cor"
version = "1.0.0"
edition = "2024"
authors = ["Cedric vaughncedriclipardoaraneta@gmail.com"]
description = "The core library for QLogicae projects"
license = "MIT"
repository = "https://github.com/CedricDeVon/qlogicae-cor"
homepage = "https://github.com/CedricDeVon/qlogicae-cor"
documentation = "https://docs.rs/qlogicae-cor"
readme = "README.md"
keywords = ["qlogicae", "framework", "library", "package", "rust"]
categories = ["development-tools"]
include = [
    "project/**",
    "src/**",
    "Cargo.toml",
    "Cargo.lock",
    "README.md",
    "LICENSE",
]

[lib]
path = "src/lib.rs"

[dependencies]
