#include "pch.hpp"

#include "utilities.hpp"

namespace QLogicaeCore
{
    Utilities::Utilities()
    {
		FULL_EXECUTABLE_FOLDER_PATH =
			SYSTEM_ACCESS.get_executable_folder();

		FULL_EXECUTED_FOLDER_PATH =
			SYSTEM_ACCESS.get_executed_folder();

		FULL_ROAMING_APPDATA_FOLDER_PATH =
			SYSTEM_ACCESS.get_roaming_appdata_folder_path();

		FULL_LOCAL_APPDATA_FOLDER_PATH =
			SYSTEM_ACCESS.get_local_appdata_folder_path();

		FULL_PROGRAMDATA_FOLDER_PATH =
			SYSTEM_ACCESS.get_programdata_folder_path();

		FULL_APPLICATION_QLOGICAE_FOLDER_PATH =
			FULL_EXECUTABLE_FOLDER_PATH;

		FULL_APPLICATION_QLOGICAE_PRIVATE_FOLDER_PATH =
			FULL_APPLICATION_QLOGICAE_FOLDER_PATH +
			"\\" + RELATIVE_DOT_QLOGICAE_FOLDER_PATH;

		FULL_APPLICATION_QLOGICAE_PUBLIC_FOLDER_PATH =
			FULL_APPLICATION_QLOGICAE_FOLDER_PATH +
			"\\" + RELATIVE_QLOGICAE_FOLDER_PATH;

		FULL_APPLICATION_QLOGICAE_PUBLIC_APPLICATION_FOLDER_PATH =
			FULL_APPLICATION_QLOGICAE_PUBLIC_FOLDER_PATH +
			"\\" + RELATIVE_APPLICATION_FOLDER_PATH;

		FULL_APPLICATION_QLOGICAE_PUBLIC_APPLICATION_CONFIGURATIONS_FOLDER_PATH =
			FULL_APPLICATION_QLOGICAE_PUBLIC_APPLICATION_FOLDER_PATH +
			"\\" + RELATIVE_CONFIGURATIONS_FOLDER_PATH;

		FULL_APPLICATION_QLOGICAE_PUBLIC_APPLICATION_CONFIGURATIONS_QLOGICAE_FILE_PATH =
			FULL_APPLICATION_QLOGICAE_PUBLIC_APPLICATION_CONFIGURATIONS_FOLDER_PATH +
			"\\" + RELATIVE_QLOGICAE_FILE_PATH;

		FULL_APPLICATION_QLOGICAE_PUBLIC_APPLICATION_CONFIGURATIONS_ENVIRONMENT_FILE_PATH =
			FULL_APPLICATION_QLOGICAE_PUBLIC_APPLICATION_CONFIGURATIONS_FOLDER_PATH +
			"\\" + RELATIVE_ENVIRONMENT_FILE_PATH;

		FULL_APPLICATION_QLOGICAE_PUBLIC_APPLICATION_ASSETS_FOLDER_PATH =
			FULL_APPLICATION_QLOGICAE_PUBLIC_APPLICATION_FOLDER_PATH +
			"\\" + RELATIVE_ASSETS_FOLDER_PATH;

		FULL_APPLICATION_QLOGICAE_PUBLIC_APPLICATION_ASSETS_APPLICATION_ICON_FILE_PATH =
			FULL_APPLICATION_QLOGICAE_PUBLIC_APPLICATION_ASSETS_FOLDER_PATH +
			"\\" + RELATIVE_APPLICATION_ICON_FILE_PATH;

		FULL_APPLICATION_QLOGICAE_PUBLIC_APPLICATION_DOCUMENTATION_FOLDER_PATH =
			FULL_APPLICATION_QLOGICAE_PUBLIC_APPLICATION_FOLDER_PATH +
			"\\" + RELATIVE_DOCUMENTATION_FOLDER_PATH;

		FULL_APPLICATION_QLOGICAE_PUBLIC_APPLICATION_DOCUMENTATION_LICENSE_FILE_PATH =
			FULL_APPLICATION_QLOGICAE_PUBLIC_APPLICATION_DOCUMENTATION_FOLDER_PATH +
			"\\" + RELATIVE_LICENSE_FILE_PATH;
    }

    Utilities& Utilities::get_instance()
    {
        static Utilities instance;

        return instance;
    }
}

