[project]
name = "qlogicae-cor"
version = "1.2.5"
description = "The core library for QLogicae projects"
readme = { file = "README.md", content-type = "text/markdown" }
requires-python = ">=3.12"
license = "MIT"
license-files = ["LICENSE"]
authors = [
    { name = "Vaughn Cedric L. Araneta", email = "vaughncedriclipardoaraneta@gmail.com" }
]
maintainers = [
    { name = "Vaughn Cedric L. Araneta", email = "vaughncedriclipardoaraneta@gmail.com" }
]
keywords = [
    "qlogicae", "cor"
]

classifiers = [
    "Development Status :: 3 - Alpha",
    "Intended Audience :: Developers",
    "Operating System :: OS Independent",
    "Programming Language :: Python",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.12",
    "Programming Language :: Python :: 3.13",
    "Programming Language :: Python :: 3.14",
    "Typing :: Typed",
    "Topic :: Software Development",
    "Topic :: Software Development :: Libraries",
    "Topic :: Software Development :: Libraries :: Python Modules",
]
dependencies = [
    "pydantic>=2.13,<3",
    "pyfiglet>=1.0.4,<2",
    "PyYAML>=6.0,<7",
    "qlogicae-cor>=1.0.8,<2",
    "rich>=15,<16",
    "textual>=8,<9",
    "typer>=0.26,<1",
    "tomli_w>=1.2.0,<2",
    "tomlkit>=0.15.0,<1"
]

[project.optional-dependencies]
dev = [
    "pytest",
    "pytest-cov",
    "pytest-benchmark",
    "ruff",
    "mypy",
    "hatch",
    "twine",
    "memray",
    "scalene",
    "pympler"
]

[project.scripts]
qlogicae-cor = "qlogicae_cor.v1.console.app:main"
qlogicae-cor-v1 = "qlogicae_cor.v1.console.app:main"

[project.urls]
Homepage = "https://github.com/CedricDeVon/qlogicae-cor"
Repository = "https://github.com/CedricDeVon/qlogicae-cor"
Documentation = "https://github.com/CedricDeVon/qlogicae-cor"
Issues = "https://github.com/CedricDeVon/qlogicae-cor/issues"
Changelog = "https://github.com/CedricDeVon/qlogicae-cor/releases"


[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"


[tool.setuptools]
package-dir = {"" = "qlogicae_cor"}


[tool.setuptools.packages.find]
where = ["qlogicae_cor"]


[tool.pytest.ini_options]
pythonpath = ["."]
testpaths = ["./test/qlogicae_cor/v1/unit"]
python_files = ["test_*.py"]
addopts = "-ra"


[tool.coverage.run]
source = [
    "qlogicae_cor.v1.value_cache_storage_manager",
    "qlogicae_cor.v1.macros_manager",
    "qlogicae_cor.v1.object_merge_manager",
    "qlogicae_cor.v1.abstract_manager",
    "qlogicae_cor.v1.singleton_manager",
    "qlogicae_cor.v1.error_manager",
]
branch = true


[tool.coverage.report]
show_missing = true
skip_covered = false


[tool.mypy]
files = ["qlogicae_cor"]
strict = true
python_version = "3.12"
namespace_packages = true
explicit_package_bases = true
show_error_codes = true
pretty = true
color_output = true
show_column_numbers = true
show_error_context = true


[tool.ruff]
target-version = "py312"
line-length = 88
exclude = [
    ".git",
    ".venv",
    "__pycache__",
    ".output",
    "output",
    ".outputs",
    "outputs",
    ".dist",
    "dist",
    ".build",
    "build",
    ".pytest_cache",
    ".ruff_cache",
    ".mypy_cache",
    ".tox",
    ".nox",
    ".idea",
    ".vscode",
]


[tool.ruff.format]
quote-style = "double"
indent-style = "space"
line-ending = "auto"
docstring-code-format = true
docstring-code-line-length = "dynamic"
skip-magic-trailing-comma = false


[tool.ruff.lint]
select = [    
    "E",
    "W", # pycodestyle    
    "F", # Pyflakes    
    "I", # isort    
    "UP", # pyupgrade    
    "B", # flake8-bugbear
    "PTH", # pathlib
]
ignore = [    
    "S607",    
    "S101", # allow assert statements    
    "S603", # allow subprocess usage
    "PLR2004", # allow magic values
]
fixable = ["ALL"]
unfixable = []


[tool.hatch.build]
include = [
    "qlogicae_cor/**/*.py",
    "qlogicae_cor/py.typed",
]
exclude = [
    "**/__pycache__/**",
    "**/*.pyc",
    ".github/**",
    "test/**",
    "docs/**",
    "project/**",
]

[tool.hatch.build.targets.wheel.force-include]
"qlogicae_cor/py.typed" = "qlogicae_cor/py.typed"


[tool.hatch.build.targets.wheel]
packages = ["qlogicae_cor"]


[tool.hatch.envs.default.scripts]
test-lint = """
    ruff check qlogicae_cor --fix
"""
test-type-check = """
    mypy
"""
test-unit = """
    pytest -vv \
        --cov \
        --cov-branch \
        --cov-report=term-missing \
        --cov-report=html:\"output/test/unit/html\" \
        --cov-report=xml:\"output/test/unit/coverage.xml\" \
        --cov-report=json:\"output/test/unit/coverage.json\" \
        --junitxml=\"output/test/unit/junit.xml\" \
"""
test-pip-deployment = """
    twine check output/build/release/dist/*
"""
deploy = """
    twine upload output/build/release/dist/* --config-file .pypirc
"""



github-workflow-setup = """
    mkdir -p output/build/release &&
    mkdir -p output/test/unit &&
    mkdir -p output/test/benchmark
"""
github-workflow-test-type-check = """
    hatch run github-workflow-setup &&
    hatch run test-type-check
"""
github-workflow-test-lint = """
    hatch run github-workflow-setup &&
    hatch run test-lint
"""
github-workflow-test-unit = """
    hatch run github-workflow-setup &&
    hatch run test-unit
"""

