name: Quality Assurance

on:
    push:
    pull_request:

defaults:
    run:
        shell: bash

jobs:
    python-unit-test:
        name: Python | Unit Test
        runs-on: ubuntu-latest

        defaults:
            run:
                working-directory: ./selection/python

        strategy:
            fail-fast: false
            matrix:
                python-version:
                    - "3.14"
                    - "3.13"
                    - "3.12"

        steps:
            - uses: actions/checkout@v4

            - name: Setup Python
              uses: actions/setup-python@v5
              with:
                python-version: ${{ matrix.python-version }}

            - name: Install Hatch
              run: |
                python -m pip install --upgrade pip
                pip install hatch

            - name: Install Dev Dependencies
              run: python3 -m pip install -r requirements.txt

            - name: Create Hatch environment
              run: hatch env create

            - name: Run unit tests              
              run: hatch run workflow-test-unit

    python-e2e-test:
      name: Python | End-To-End Test
      runs-on: ubuntu-latest

      defaults:
          run:
              working-directory: ./selection/python

      strategy:
          fail-fast: false
          matrix:
              python-version:
                  - "3.14"
                  - "3.13"
                  - "3.12"

      steps:
          - uses: actions/checkout@v4

          - name: PyPi Wait
            run: sleep 30

          - name: Setup Python
            uses: actions/setup-python@v5
            with:
                python-version: ${{ matrix.python-version }}

          - name: Setup Virtual Environment
            run: python3 -m venv .venv

          - name: Activate Virtual Environment
            run: source .venv/bin/activate

          - name: Install Package
            run: pip install qlogicae-cor

          - name: Run Package Existence Validation
            run: qlogicae-cor

          - name: Run End-to-End Test
            run: python test/e2e/usage.py

    python-install:
        name: Python | Install via ${{ matrix.package_manager }} on Python ${{ matrix.python-version }}
        runs-on: ubuntu-latest

        defaults:
            run:
                working-directory: ./selection/python

        strategy:
            fail-fast: false
            matrix:
                python-version:
                    - "3.14"
                    - "3.13"
                    - "3.12"

                package_manager:
                    - pip
                    - uv
                    - conda
                    - poetry
                    - pdm
                    - hatch

        steps:
            - uses: actions/checkout@v4

            - uses: actions/setup-python@v5
              with:
                python-version: ${{ matrix.python-version }}

            - name: Install pip tools
              run: python -m pip install --upgrade pip

            - if: ${{ matrix.package_manager == 'uv' }}
              run: pip install uv

            - if: ${{ matrix.package-manager == 'conda' }}
              uses: conda-incubator/setup-miniconda@v3
              with:
                python-version: ${{ matrix.python-version }}
                activate-environment: test
                auto-activate-base: false

            - if: ${{ matrix.package_manager == 'poetry' }}
              run: |
                pip install poetry
                poetry install --no-root
                poetry run python -c "import library"

            - if: ${{ matrix.package_manager == 'pdm' }}
              run: pip install pdm

            - if: ${{ matrix.package_manager == 'hatch' }}
              run: pip install hatch

            - name: Build package
              run: |
                pip install hatch
                hatch run build

            - if: ${{ matrix.package_manager == 'pip' }}
              run: pip install ./output/build/*.whl

            - if: ${{ matrix.package_manager == 'uv' }}
              run: uv pip install --system ./output/build/*.whl

            - if: ${{ matrix.package-manager == 'conda' }}
              shell: bash -l {0}
              run: |
                conda install pip -y
                pip install output/build/*.whl
                
            - if: ${{ matrix.package_manager == 'poetry' }}
              run: pip install ./output/build/*.whl

            - if: ${{ matrix.package_manager == 'pdm' }}
              run: pdm init --non-interactive
                && pdm add ./output/build/*.whl

            - if: ${{ matrix.package_manager == 'hatch' }}
              run: |
                python -m venv venv
                . venv/bin/activate
                pip install ./output/build/*.whl

            - name: Verify installation
              run: python -c "import library"

    typescript-unit-test:
        name: Typescript | Unit Test
        runs-on: ubuntu-latest

        defaults:
            run:
                working-directory: ./selection/typescript

        steps:
            - uses: actions/checkout@v4

            - uses: oven-sh/setup-bun@v2
              with:
                  bun-version: latest

            - run: bun install --frozen-lockfile
            - run: bun run workflow:test:unit

    typescript-install:
        name: Typescript | Install via ${{ matrix.package_manager }} on Node ${{ matrix.node_version }}
        runs-on: ubuntu-latest

        strategy:
            fail-fast: false
            matrix:
                node_version: [22, 24]
                package_manager:
                    - npm
                    - pnpm
                    - yarn
                    - bun

        steps:
            - if: matrix.package_manager == 'npm'
              uses: actions/setup-node@v4
              with:
                  node-version: ${{ matrix.node_version }}

            - if: matrix.package_manager == 'pnpm'
              uses: pnpm/action-setup@v4
              with:
                  version: latest

            - if: matrix.package_manager == 'pnpm'
              uses: actions/setup-node@v4
              with:
                  node-version: ${{ matrix.node_version }}

            - if: matrix.package_manager == 'yarn'
              uses: actions/setup-node@v4
              with:
                  node-version: ${{ matrix.node_version }}

            - if: matrix.package_manager == 'bun'
              uses: oven-sh/setup-bun@v2
              with:
                  bun-version: latest

            - run: sleep 15

            - if: matrix.package_manager == 'npm'
              run: npm install qlogicae-cor1@latest

            - if: matrix.package_manager == 'pnpm'
              run: pnpm add qlogicae-cor1@latest

            - if: matrix.package_manager == 'yarn'
              run: yarn add qlogicae-cor1@latest

            - if: matrix.package_manager == 'bun'
              run: bun add qlogicae-cor1@latest
